### PR TITLE
MOTOR-1215: Replaced all usage of utcnow with .now(datetime.timezone.utc)

### PR DESCRIPTION
**Pull request by Jibola**

### CODE REVIEW

**Comment by caseyclements** [comment]
Hi @Jibola This generally LGTM. Are all the tests failing with a `DeprecationWarning` that is precisely what this PR is meant to remove? 🤣 Do we expect these?

**Comment by Jibola** [comment]
> Hi @Jibola This generally LGTM. Are all the tests failing with a `DeprecationWarning` that is precisely what this PR is meant to remove? 🤣 Do we expect these?

Yeah, turns out the remaining `DeprecationWarning`s are from third-party libraries, so I've returned the filterwarning check.

**Comment by caseyclements** [comment]
Great. Good to go then.

**Review by caseyclements — APPROVED** [review]
LGTM

**Pull request merged**
