### PR TITLE
MOTOR-1098 Skip synchro test_typing and encrypted coll tests on standalones

### PR DESCRIPTION
**Pull request by ShaneHarvey**
Resolves https://jira.mongodb.org/browse/MOTOR-1098

### CODE REVIEW

**Comment by ShaneHarvey** [comment]
New errors are due to existing issues. A snapshot query change on latest:
```
 [2023/04/05 21:47:16.970] ERROR [0.043s]: test_snapshot_query (asyncio_tests.test_examples.TestExamples)
 [2023/04/05 21:47:16.970] ----------------------------------------------------------------------
 [2023/04/05 21:47:16.970] Traceback (most recent call last):
 [2023/04/05 21:47:16.970]   File "/data/mci/5f14d1101c0af7050000b672509394c7/src/test/asyncio_tests/__init__.py", line 49, in __call__
 [2023/04/05 21:47:16.970]     result = self.orig_method()
 [2023/04/05 21:47:16.970]   File "/data/mci/5f14d1101c0af7050000b672509394c7/src/test/test_environment.py", line 305, in wrap
 [2023/04/05 21:47:16.970]     return f(*args, **kwargs)
 [2023/04/05 21:47:16.970]   File "/data/mci/5f14d1101c0af7050000b672509394c7/src/test/asyncio_tests/__init__.py", line 211, in wrapped
 [2023/04/05 21:47:16.970]     self.loop.run_until_complete(task)
 [2023/04/05 21:47:16.970]   File "/opt/python/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
 [2023/04/05 21:47:16.970]     return future.result()
 [2023/04/05 21:47:16.970]   File "/opt/python/3.8/lib/python3.8/asyncio/tasks.py", line 494, in wait_for
 [2023/04/05 21:47:16.970]     return fut.result()
 [2023/04/05 21:47:16.970]   File "/data/mci/5f14d1101c0af7050000b672509394c7/src/test/asyncio_tests/test_examples.py", line 1343, in test_snapshot_query
 [2023/04/05 21:47:16.970]     adoptablePetsCount = docs[0]["adoptableCatsCount"]
 [2023/04/05 21:47:16.970] IndexError: list index out of range
 [2023/04/05 21:47:16.970]
```
And a QE change on latest:
```
 [2023/04/05 21:47:16.970] ERROR [0.724s]: test_queryable_encryption (asyncio_tests.test_examples.TestQueryableEncryptionDocsExample)
 [2023/04/05 21:47:16.970] ----------------------------------------------------------------------
 [2023/04/05 21:47:16.970] Traceback (most recent call last):
 [2023/04/05 21:47:16.970]   File "/data/mci/5f14d1101c0af7050000b672509394c7/src/test/asyncio_tests/__init__.py", line 49, in __call__
 [2023/04/05 21:47:16.970]     result = self.orig_method()
 [2023/04/05 21:47:16.970]   File "/data/mci/5f14d1101c0af7050000b672509394c7/src/test/test_environment.py", line 305, in wrap
 [2023/04/05 21:47:16.970]     return f(*args, **kwargs)
 [2023/04/05 21:47:16.970]   File "/data/mci/5f14d1101c0af7050000b672509394c7/src/test/asyncio_tests/__init__.py", line 211, in wrapped
 [2023/04/05 21:47:16.970]     self.loop.run_until_complete(task)
 [2023/04/05 21:47:16.970]   File "/opt/python/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
 [2023/04/05 21:47:16.970]     return future.result()
 [2023/04/05 21:47:16.970]   File "/opt/python/3.8/lib/python3.8/asyncio/tasks.py", line 494, in wait_for
 [2023/04/05 21:47:16.970]     return fut.result()
 [2023/04/05 21:47:16.970]   File "/data/mci/5f14d1101c0af7050000b672509394c7/src/test/asyncio_tests/test_examples.py", line 1485, in test_queryable_encryption
 [2023/04/05 21:47:16.970]     await encrypted_coll.insert_one(
 [2023/04/05 21:47:16.970]   File "/opt/python/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
 [2023/04/05 21:47:16.970]     result = self.fn(*self.args, **self.kwargs)
 [2023/04/05 21:47:16.970]   File "/data/mci/5f14d1101c0af7050000b672509394c7/src/.tox/asyncio-py38/lib/python3.8/site-packages/pymongo/collection.py", line 628, in insert_one
 [2023/04/05 21:47:16.970]     self._insert_one(
 [2023/04/05 21:47:16.970]   File "/data/mci/5f14d1101c0af7050000b672509394c7/src/.tox/asyncio-py38/lib/python3.8/site-packages/pymongo/collection.py", line 569, in _insert_one
 [2023/04/05 21:47:16.970]     self.__database.client._retryable_write(acknowledged, _insert_command, session)
 [2023/04/05 21:47:16.970]   File "/data/mci/5f14d1101c0af7050000b672509394c7/src/.tox/asyncio-py38/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1476, in _retryable_write
 [2023/04/05 21:47:16.970]     return self._retry_with_session(retryable, func, s, None)
 [2023/04/05 21:47:16.970]   File "/data/mci/5f14d1101c0af7050000b672509394c7/src/.tox/asyncio-py38/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1349, in _retry_with_session
 [2023/04/05 21:47:16.970]     return self._retry_internal(retryable, func, session, bulk)
 [2023/04/05 21:47:16.970]   File "/data/mci/5f14d1101c0af7050000b672509394c7/src/.tox/asyncio-py38/lib/python3.8/site-packages/pymongo/_csot.py", line 105, in csot_wrapper
 [2023/04/05 21:47:16.970]     return func(self, *args, **kwargs)
 [2023/04/05 21:47:16.970]   File "/data/mci/5f14d1101c0af7050000b672509394c7/src/.tox/asyncio-py38/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1390, in _retry_internal
 [2023/04/05 21:47:16.970]     return func(session, sock_info, retryable)
 [2023/04/05 21:47:16.970]   File "/data/mci/5f14d1101c0af7050000b672509394c7/src/.tox/asyncio-py38/lib/python3.8/site-packages/pymongo/collection.py", line 557, in _insert_command
 [2023/04/05 21:47:16.970]     result = sock_info.command(
 [2023/04/05 21:47:16.970]   File "/data/mci/5f14d1101c0af7050000b672509394c7/src/.tox/asyncio-py38/lib/python3.8/site-packages/pymongo/pool.py", line 767, in command
 [2023/04/05 21:47:16.970]     return command(
 [2023/04/05 21:47:16.970]   File "/data/mci/5f14d1101c0af7050000b672509394c7/src/.tox/asyncio-py38/lib/python3.8/site-packages/pymongo/network.py", line 166, in command
 [2023/04/05 21:47:16.970]     helpers._check_command_response(
 [2023/04/05 21:47:16.971]   File "/data/mci/5f14d1101c0af7050000b672509394c7/src/.tox/asyncio-py38/lib/python3.8/site-packages/pymongo/helpers.py", line 181, in _check_command_response
 [2023/04/05 21:47:16.971]     raise OperationFailure(errmsg, code, response, max_wire_version)
 [2023/04/05 21:47:16.971] pymongo.errors.OperationFailure: Encountered a Queryable Encryption insert/update payload type that is no longer supported, full error: {'ok': 0.0, 'errmsg': 'Encountered a Queryable Encryption insert/update payload type that is no longer supported', 'code': 7291901, 'codeName': 'Location7291901', '$clusterTime': {'clusterTime': Timestamp(1680731236, 28), 'signature': {'hash': b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'keyId': 0}}, 'operationTime': Timestamp(1680731236, 28)}
```

**Comment by blink1073** [comment]
Looks like the QE failure will be fixed by https://jira.mongodb.org/browse/MOTOR-1100, do we need a new ticket for the snapshot failure?

**Comment by blink1073** [comment]
Looks like another failure:

test.test_encryption.TestKmsTLSOptions.test_05_tlsDisableOCSPEndpointCheck_is_permitted

```
 [2023/04/06 17:44:06.841] ERROR: 'ClientEncryption' object has no attribute '_io_callbacks' (builtins.AttributeError)
 [2023/04/06 17:44:06.841] Traceback (most recent call last):
 [2023/04/06 17:44:06.841]   File "/opt/python/3.7/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
 [2023/04/06 17:44:06.841]     yield
 [2023/04/06 17:44:06.841]   File "/opt/python/3.7/lib/python3.7/unittest/case.py", line 628, in run
 [2023/04/06 17:44:06.841]     testMethod()
 [2023/04/06 17:44:06.841]   File "/data/mci/1dffd892ba14e99364797220f670957e/src/.tox/synchro37/tmp/mongo-python-driver/test/test_encryption.py", line 2163, in test_05_tlsDisableOCSPEndpointCheck_is_permitted
 [2023/04/06 17:44:06.841]     ctx = encryption._io_callbacks.opts._kms_ssl_contexts["aws"]
 [2023/04/06 17:44:06.841] AttributeError: 'ClientEncryption' object has no attribute '_io_callbacks'
```

**Comment by ShaneHarvey** [comment]
Running a new patch to confirm syncrho passes.

**Review by blink1073 — APPROVED** [review]
LGTM!

**Pull request merged**
