### PR TITLE
MOTOR-1299 Add SBOM-lite and CodeQL files

### PR DESCRIPTION
**Pull request by blink1073**

### CODE REVIEW

**Comment by blink1073** [comment]
I opened https://jira.mongodb.org/browse/MOTOR-1322 to track the failures which were caused by an upstream change in PyMongo.

**Comment by caseyclements** [comment]
So, the failures are red herrings, and this is good to go?

**Comment by blink1073** [comment]
> So, the failures are red herrings, and this is good to go?

Yes, but I just pulled in #284 to verify.

**Review by caseyclements — APPROVED** [review]
LGTM

**Pull request merged**
