### PR TITLE
MOTOR-40 Example using aiohttp.

### PR DESCRIPTION
**Pull request by ajdavis**
@asvetlov, thanks to you and @jettify, Motor 0.5 with asyncio is close to release. Could you review this example application that I plan to include in the tutorial?

The docs are rendered here:

http://emptysqua.re/aiotthp-example-docs/tutorial-asyncio.html#a-web-application-with-aiohttp

[Review on Reviewable](https://reviewable.io/reviews/mongodb/motor/22)

### CODE REVIEW

**Comment by jettify** [comment]
Thanks @ajdavis ! I would put mongo connection to `web.Application` , it has dict interface designed to hold database connections and any things to share between handlers. For example:

```python
@asyncio.coroutine
def create_example_server(loop):
    app = web.Application(loop=loop)
    db = yield from setup_db()
    app['db'] = db
    app.router.add_route('GET', '/pages/{page_name}', page)
    srv = yield from loop.create_server(app.make_handler(), '127.0.0.1', 8080)
    return srv
```

and then in handler:
```python
@asyncio.coroutine
def page(request):
    db = request.app['db']
    page_name = request.match_info.get('page_name')
    document = yield from db.pages.find_one(page_name)
    ...
```
see also example in docs: http://aiohttp.readthedocs.org/en/latest/web_reference.html#application

**Comment by asvetlov** [comment]
Agree with @jettify

**Comment by ajdavis** [comment]
Updated, thanks for your advice. The documentation is updated here:

http://emptysqua.re/aiotthp-example-docs/tutorial-asyncio.html#a-web-application-with-aiohttp

**Comment by asvetlov** [comment]
Would you add proper server finalization?
It should looks like:
```
handler = app.make_handler()
f = loop.create_server(handler, '0.0.0.0', 8080)
srv = loop.run_until_complete(f)
main_socket = srv.sockets[0]
print('serving on', srv.sockets[0].getsockname())
try:
    loop.run_forever()
except KeyboardInterrupt:
    pass
main_socket.close()
await handler.finish_connections()
await app.finish()
```

**Comment by asvetlov** [comment]
The main idea for finalization is: close passive (accepting) socket and wait for finishing all current connections. For streaming/websockets user should do more work.

**Comment by ajdavis** [comment]
Updated. The docs are regenerated here:

http://emptysqua.re/aiotthp-example-docs/tutorial-asyncio.html#a-web-application-with-aiohttp

I tried to package all the shutdown steps into a coroutine, did I do that correctly?

**Comment by ajdavis** [comment]
Here is the actual code:

https://github.com/mongodb/motor/blob/aiohttp-example/doc/examples/aiohttp_example.py#L57

**Comment by ajdavis** [comment]
Hey @jettify and @asvetlov I plan to merge this, could you take a final look at my aiohttp server finalization code and tell me if it's correct? Is there no simpler way to do it?

**Comment by ajdavis** [comment]
Updated to close the listening socket before `handler.finish_connections`.

**Comment by asvetlov** [comment]
Looks good

**Comment by ajdavis** [comment]
Thanks!

**Pull request merged**
