### PR TITLE
MOTOR-981 Test Failure - asyncio_tests.test_asyncio_session.TestAsyncIOSession.test_collection

### PR DESCRIPTION
**Pull request by blink1073**

### CODE REVIEW

**Comment by blink1073** [comment]
I scheduled all the sharded macos tasks.

**Comment by blink1073** [comment]
All tests are passing.   The task that had failed yesterday was a startup failure and not related.

**Review by ShaneHarvey — APPROVED** [review]
Any ideas for why this test is so slow?

**Comment by blink1073** [comment]
> Any ideas for why this test is so slow?

No, I ran the same setup locally and it was snappy.  I'm assuming the Evergreen hosts are underpowered comparatively.

**Pull request merged**
