### PR TITLE
Asyncio

### PR DESCRIPTION
**Pull request by rejoc**
Merge asyncio with r04 in order to use PyMongo 2.8

### CODE REVIEW

**Comment by ajdavis** [comment]
Hi, this is just to say I haven't forgotten about this pull request. I'm very grateful for your effort and I plan to merge it. asyncio support in Motor just didn't make it onto my goals this quarter.

**Comment by imbolc** [comment]
Wow, im so excited :) When are you planning to merge it?

**Comment by ajdavis** [comment]
Next quarter, unfortunately -- this quarter I can't allow any distractions from MongoDB C Driver development. Merging this will certainly be the first step toward Motor 0.5, however. Sorry for the delay, and thanks so much for the work you've done.

**Comment by ajdavis** [comment]
@rejoc what's your name please? I'd like to thank you in Motor's release notes and list you on the contributors page.

Thank you!

**Comment by iho** [comment]
How to play with it? It is usable?

**Comment by ajdavis** [comment]
It is usable. Install Motor from master:
```
pip install git+git://github.com/mongodb/motor.git
```

**Comment by ajdavis** [comment]
Merged in https://github.com/mongodb/motor/commit/cf956948e6ca074bbf62587ea5f844880a9c1550 , thanks @rejoc !

**Pull request closed without merging**
