### PR TITLE
MOTOR-613: Add contextvars support

### PR DESCRIPTION
**Pull request by khasanovbi**
Add support to context vars.

This may be useful for logging, e.g. pass trace params like request_id to CommandLogger

### CODE REVIEW

**Comment by ShaneHarvey** [comment]
Neat! I was just having a conversation with a colleague about using `contextvars` in Motor the other week! 

> This may be useful for logging, e.g. pass trace params like request_id to CommandLogger

Any chance you can provide an example use case?

**Comment by khasanovbi** [comment]
> Any chance you can provide an example use case?

Yep

```python
import contextvars
import logging
import logging.config
import uuid
from typing import Awaitable, Callable

from aiohttp import web
from aiohttp.web_middlewares import middleware
from aiohttp.web_request import Request
from aiohttp.web_response import StreamResponse
from motor.motor_asyncio import AsyncIOMotorClient
from pymongo import monitoring
from pymongo.monitoring import (
    CommandFailedEvent,
    CommandStartedEvent,
    CommandSucceededEvent,
)

logger = logging.getLogger(__name__)

request_id_var = contextvars.ContextVar("request_id", default=0)


@middleware
async def request_id_middleware(
    request: Request, handler: Callable[[Request], Awaitable[StreamResponse]]
) -> StreamResponse:
    request_id = request.headers.get("X-Request-Id")
    if not request_id:
        request_id = int(uuid.uuid4().hex[:16], 16)
    request_id_var.set(request_id)
    return await handler(request)


class RequestContextFilter(logging.Filter):
    def filter(self, record: logging.LogRecord) -> bool:
        record.request_id = request_id_var.get()  # type: ignore
        return True


class CommandLogger(monitoring.CommandListener):
    def started(self, event: CommandStartedEvent) -> None:
        logger.debug(
            "mongo command started: command='%s', operation_id=%s, connection_id=%s",
            event.command_name,
            event.operation_id,
            event.connection_id,
        )

    def succeeded(self, event: CommandSucceededEvent) -> None:
        logger.info(
            "mongo command succeeded: command='%s', duration=%s, operation_id=%s, connection_id=%s",
            event.command_name,
            event.duration_micros,
            event.operation_id,
            event.connection_id,
        )

    def failed(self, event: CommandFailedEvent) -> None:
        logger.error(
            "mongo command failed: command='%s', duration=%s, operation_id=%s, connection_id=%s, failure=%s",
            event.command_name,
            event.duration_micros,
            event.operation_id,
            event.connection_id,
            event.failure,
        )


async def ping_handler(request: Request) -> StreamResponse:
    logger.info("start ping request")
    result = await request.app["mongo"].admin.command("ping")
    is_success = bool(result["ok"])
    logger.info("got ping result: result=%s", is_success)
    if is_success:
        return web.Response(text="OK")
    else:
        return web.Response(text="Error", status=500)


def main() -> None:
    logging.config.dictConfig(
        {
            "version": 1,
            "disable_existing_loggers": False,
            "filters": {"request_context_filter": {"()": RequestContextFilter}},
            "formatters": {
                "console": {
                    "()": "logging.Formatter",
                    "style": "{",
                    "format": "[{asctime}] {filename}:{lineno} {levelname} {request_id:0>16x} - {message}",
                },
            },
            "handlers": {
                "console": {
                    "level": "DEBUG",
                    "class": "logging.StreamHandler",
                    "stream": "ext://sys.stdout",
                    "formatter": "console",
                    "filters": ["request_context_filter"],
                },
            },
            "root": {"level": "DEBUG", "handlers": ["console"]},
        }
    )
    mongo_client = AsyncIOMotorClient(
        host="mongodb://localhost:27011,localhost:27012,localhost:27013/?replicaSet=rs0",
        event_listeners=[CommandLogger()],
    )
    app = web.Application(middlewares=[request_id_middleware])
    app["mongo"] = mongo_client
    app.router.add_get("/", ping_handler)
    web.run_app(app)


if __name__ == "__main__":
    main()


# OUTPUT:
# [2020-08-26 02:15:02,413] selector_events.py:59 DEBUG 0000000000000000 - Using selector: KqueueSelector
# ======== Running on http://0.0.0.0:8080 ========
# (Press CTRL+C to quit)
# [2020-08-26 02:15:05,891] logger.py:71 INFO ffff2f3d0da94374 - start ping request
# [2020-08-26 02:15:06,008] logger.py:43 DEBUG ffff2f3d0da94374 - mongo command started: command='ping', operation_id=74243042, connection_id=('localhost', 27011)
# [2020-08-26 02:15:06,011] logger.py:51 INFO ffff2f3d0da94374 - mongo command succeeded: command='ping', duration=2964, operation_id=74243042, connection_id=('localhost', 27011)
# [2020-08-26 02:15:06,011] logger.py:74 INFO ffff2f3d0da94374 - got ping result: result=True
# [2020-08-26 02:15:06,012] web_log.py:233 INFO 0000000000000000 - 127.0.0.1 [25/Aug/2020:23:15:05 +0000] "GET / HTTP/1.1" 200 152 "-" "curl/7.64.1"

```

**Comment by khasanovbi** [comment]
@ShaneHarvey is it ok?

**Review by ShaneHarvey — APPROVED** [review]

**Comment by ShaneHarvey** [comment]
Thanks @khasanovbi!

**Comment by ShaneHarvey** [comment]
@khasanovbi you may be interested to learn this feature was released in version 2.3.0 today, see https://developer.mongodb.com/community/forums/t/motor-2-3-0-released/9638.

**Pull request merged**
