### PR TITLE
MOTOR-622: Add Python 3.9 support

### PR DESCRIPTION
**Pull request by guanlinzhou**
Run Test suite on Python 3.9, add Python 3.9 to evergreen test matrix and travis builds

### CODE REVIEW

**Comment by ShaneHarvey** [comment]
Neat, could you schedule the py39 tasks in evergreen?

**Comment by guanlinzhou** [comment]
> Neat, could you schedule the py39 tasks in evergreen?

done!

**Comment by ShaneHarvey** [comment]
Sorry, one more thing I just remembered. Can you add `Programming Language :: Python :: 3.8` here:
https://github.com/mongodb/motor/blob/master/setup.py#L18

This tells pypi that we support 3.9.

**Comment by guanlinzhou** [comment]
> Sorry, one more thing I just remembered. Can you add `Programming Language :: Python :: 3.9` here:
> https://github.com/mongodb/motor/blob/master/setup.py#L18
> 
> This tells pypi that we support 3.9.

done!

**Review by prashantmital — APPROVED** [review]

**Review by ShaneHarvey — APPROVED** [review]

**Pull request merged**
